name: deploy_API_Staging

on:

   workflow_dispatch:
 
   
jobs:
   
   pull_image:
     runs-on: [self-hosted, farmy_aws]

     steps:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-1
      
       - name: install aws cli
         uses: chrislennon/action-aws-cli@v1.1
         
       - run: test aws cli _ aws s3 ls
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            
       - name: AWS EC2 Start and Stop
         uses: flyweightrocks/aws-ec2-action@v1
         with:
            instance-id: i-0444e8a732900883a
            wait-instance-running: true
            stop-instance: true      
         
       - name : initialization and some checks
         run: |
            cd $HOME
            pwd
            ls
            
       - name: pull API image
         run: |
          sudo docker pull khaldi22/api_imag
          sudo docker images
          
       - name: Run model api docker 
         run: |
            sudo docker rm -f api_staging && sudo docker run -di --name api_staging -p 80:8080  khaldi22/api_imag  
            
         
       - name: launch performance testing (faire un fichier special au api)
         run: | 
            echo do_it_later
            #cd $HOME
            #ls
            #rm -r reportmy.html
            #rm resultjmeter.csv
            #./apache-jmeter-5.5/bin/jmeter -n -t test_nginx_server_gcp.jmx  -l  resultjmeter.csv   -e -o reportmy.html
       - name: API deployed seccussfuly to staging please (verify performance report)
         run: |
            echo "upload report to s3/ un dossier avec le timestamp_staging" 


         
