name: deploy_API_Staging

on:

   pull_request:
    branches: [ "develo" ]

   workflow_dispatch:
   
#env: 
#   docker_user: ${{ secrets.DOCKERHUB_USERNAME}}
#   docker_password: ${{ secrets.DOCKERHUB_PASSWORD}}
   
jobs:
   
   pull_image:
     #runs-on: ubuntu-latest
     runs-on: self-hosted

     steps:
#       - uses: actions/checkout@v3

#       - name: docker login
#         run: |
#            docker login -u $docker_user -p $docker_password
#       - name: pull MLflow server image
#         run: |
#          docker pull scbnf99/mlflow:latest
#          docker images
       - name : initialization and some checks
         run: |
            cd $HOME
            pwd
            ls
            
       - name: pull API image
         run: |
          sudo docker pull khaldi22/api_imag
          sudo docker images
       - name: Run model api docker 
         run: |
            sudo docker rm -f api_staging && sudo docker run -di --name api_staging -p 80:8080  khaldi22/api_imag  
            
       - name: test if the api is started 
         run:  curl http://127.0.0.1
         
       - name: launch performance testing (faire un fichier special au api)
         run: | 
            echo do_it_later
            #cd $HOME
            #ls
            #rm -r reportmy.html
            #rm resultjmeter.csv
            #./apache-jmeter-5.5/bin/jmeter -n -t test_nginx_server_gcp.jmx  -l  resultjmeter.csv   -e -o reportmy.html
       - name: API deployed seccussfuly to staging please (verify performance report)
         run: |
            echo "upload report to s3/ un dossier avec le timestamp_staging" 


         
