name: deploy_API_Staging

on:

   pull_request:
    branches: [ "develo" ]

   workflow_dispatch:
 
   
jobs:
   
   pull_image:
     runs-on: self-hosted

     steps:
       - name : initialization and some checks
         run: |
            cd $HOME
            pwd
            ls
            
       - name: pull API image
         run: |
          sudo docker pull khaldi22/api_imag
          sudo docker images
          
       - name: Run model api docker 
         run: |
            sudo docker rm -f api_staging && sudo docker run -di --name api_staging -p 80:8080  khaldi22/api_imag  
            
         
       - name: launch performance testing (faire un fichier special au api)
         run: | 
            echo do_it_later
            #cd $HOME
            #ls
            #rm -r reportmy.html
            #rm resultjmeter.csv
            #./apache-jmeter-5.5/bin/jmeter -n -t test_nginx_server_gcp.jmx  -l  resultjmeter.csv   -e -o reportmy.html
       - name: API deployed seccussfuly to staging please (verify performance report)
         run: |
            echo "upload report to s3/ un dossier avec le timestamp_staging" 


         
