 
vars:
  # all path start from the root directory "farmy_cv_mlops" 
  - src:  ../../src
  - data: ../../data/small_dataset
  - results: ../../ml_pipelines/plant_disease_pipeline/results
  - res: # results
      tr:
        history: ../../ml_pipelines/plant_disease_pipeline/results/training/history
        model  : ../../ml_pipelines/plant_disease_pipeline/results/training/model

      exp:
        plots:   ../../ml_pipelines/plant_disease_pipeline/results/exploratory/exploratory_img/plots

      eval:
        csv:  ../../ml_pipelines/plant_disease_pipeline/results/evaluate/evaluate_csv
        plots:   ../../ml_pipelines/plant_disease_pipeline/results/evaluate/evaluate_plt
 



stages:
  exploratory:
    cmd: 
      - python   ${src}/exploratory.py  ${data}/train/  ${data}/val/   ${res.exp.plots}/

    deps:
    -   ${data}/train/
    -   ${data}/val/
    -   ${src}/exploratory.py
    outs:
    -   ${res.exp.plots}/train.png
    -   ${res.exp.plots}/valid.png



  train:
    cmd: 
      - python   ${src}/train.py   ${data}/train/   ${data}/val/   ${res.tr.model} ${res.tr.history}   ${results}
      #train_data_path = sys.argv[1] #  traing data path
      #validation_data_path = sys.argv[2] #  validation data path
      #output_model_path = sys.argv[3]    # model artifact folder path: where we stock the model 
      #output_history_path= sys.argv[4]   # history folder path : where we stock this file
      #run_info_path= sys.argv[5]   #  the path where to save run_info.json :
   
    deps:
    -   ${src}/train.py 
    -   ${data}/train/
    -   ${data}/val/    
    params:
    - train.batch_size
    - train.learning_rate
    - train.momentum
    - train.nbr_epoch
    outs:
    -   ${res.tr.model}
    -   ${res.tr.history}/history.csv
    -   ${results}/run_info.json     



  evaluate:
    cmd: python   ${src}/evaluate.py   ${results}/training/keras   ${results}/training/history/history.csv  \
         ${data}/val/   ${results}/evaluate/evaluate_csv/classification_report.csv   data/small_dataset/train/ \
         ${results}/evaluate/evaluate_csv/confusion_matrix.csv   ${results}/evaluate/evaluate_plt/confusion_matrix_img.png \
         ${results}/evaluate/evaluate_plt/observing_accuracy_img.png   ${results}/exploratory/exploratory_img/plots/
    deps:
    -   ${results}/training/keras
    -   ${results}/training/history/history.csv
    -   ${data}/train
    -   ${data}val
    -   ${src}/evaluate.py
    
    outs:
     -   ${results}/evaluate/evaluate_csv/classification_report.csv
     -   ${results}/evaluate/evaluate_csv/confusion_matrix.csv
     -   ${results}/evaluate/evaluate_plt/confusion_matrix_img.png 
     -   ${results}/evaluate/evaluate_plt/observing_accuracy_img.png
 

